<../../../../../../../mkconfig

TARG=\
	Constants.dis\
	JrmpGenerator.dis\
	RemoteClass.dis\
	StubSkeletonWriter.dis\
	Util.dis\

DISBIN=$ROOT/java/dis/java/java/sun/rmi/rmic/newrmic/jrmp

<$ROOT/mkfiles/mkjava
