<../../../../../../mkconfig

TARG=\
	AccelDeviceEventListener.dis\
	AccelDeviceEventNotifier.dis\
	AccelGraphicsConfig.dis\
	AccelSurface.dis\
	AccelTypedVolatileImage.dis\
	BufferedContextProvider.dis\
	ContextCapabilities.dis\
	ExtendedBufferCapabilities.dis\

DISBIN=$ROOT/java/dis/java/java/sun/java2d/pipe/hw

<$ROOT/mkfiles/mkjava
