<../../../../../../../mkconfig

TARG=\
	DigestMD5Base.dis\
	DigestMD5Client.dis\
	DigestMD5Server.dis\
	FactoryImpl.dis\
	SecurityCtx.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/security/sasl/digest

<$ROOT/mkfiles/mkjava
