<../../../../../mkconfig

TARG=\
	AreaOp.dis\
	ChainEnd.dis\
	Crossings.dis\
	Curve.dis\
	CurveLink.dis\
	Edge.dis\
	Order0.dis\
	Order1.dis\
	Order2.dis\
	Order3.dis\
	PathConsumer2D.dis\

DISBIN=$ROOT/java/dis/java/java/sun/awt/geom

<$ROOT/mkfiles/mkjava
