<../../../../../mkconfig

TARG=\
	AbstractPreferences.dis\
	BackingStoreException.dis\
	Base64.dis\
	InvalidPreferencesFormatException.dis\
	NodeChangeEvent.dis\
	NodeChangeListener.dis\
	PreferenceChangeEvent.dis\
	PreferenceChangeListener.dis\
	Preferences.dis\
	PreferencesFactory.dis\
	XmlSupport.dis\

DISBIN=$ROOT/java/dis/java/java/java/util/prefs

<$ROOT/mkfiles/mkjava
