<../../../../../mkconfig

TARG=\
	AbstractBorder.dis\
	BevelBorder.dis\
	Border.dis\
	CompoundBorder.dis\
	EmptyBorder.dis\
	EtchedBorder.dis\
	LineBorder.dis\
	MatteBorder.dis\
	SoftBevelBorder.dis\
	StrokeBorder.dis\
	TitledBorder.dis\

DISBIN=$ROOT/java/dis/java/java/javax/swing/border

<$ROOT/mkfiles/mkjava
