<../../../../../../../../mkconfig

TARG=\
	ArraySorter.dis\
	Comparer.dis\
	CompositeEnumeration.dis\
	Misc.dis\
	VectorSorter.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/tools/hat/internal/util

<$ROOT/mkfiles/mkjava
