<../../../../../mkconfig

TARG=\
	GetBooleanAction.dis\
	GetBooleanSecurityPropertyAction.dis\
	GetIntegerAction.dis\
	GetLongAction.dis\
	GetPropertyAction.dis\
	LoadLibraryAction.dis\
	OpenFileInputStreamAction.dis\
	PutAllAction.dis\

DISBIN=$ROOT/java/dis/java/java/sun/security/action

<$ROOT/mkfiles/mkjava
