<../../../../../mkconfig

TARG=\
	CompositionArea.dis\
	CompositionAreaHandler.dis\
	InputContext.dis\
	InputMethodAdapter.dis\
	InputMethodContext.dis\
	InputMethodJFrame.dis\
	InputMethodLocator.dis\
	InputMethodManager.dis\
	InputMethodPopupMenu.dis\
	InputMethodWindow.dis\
	SimpleInputMethodWindow.dis\

DISBIN=$ROOT/java/dis/java/java/sun/awt/im

<$ROOT/mkfiles/mkjava
