<../../../../../../mkconfig

TARG=\
	ChunkedInputStream.dis\
	ChunkedOutputStream.dis\
	HttpCapture.dis\
	HttpCaptureInputStream.dis\
	HttpCaptureOutputStream.dis\
	HttpClient.dis\
	Hurryable.dis\
	KeepAliveCache.dis\
	KeepAliveStream.dis\
	KeepAliveStreamCleaner.dis\
	PosterOutputStream.dis\

DISBIN=$ROOT/java/dis/java/java/sun/net/www/http

<$ROOT/mkfiles/mkjava
