<../../../../../../mkconfig

TARG=\
	ArgsAttributes.dis\
	Attributes.dis\
	DependencyClass.dis\
	FunctionAttributes.dis\
	FunctionName.dis\
	ModuleAttributes.dis\
	ModuleName.dis\
	NameAttributes.dis\
	package-info.dis\
	ProviderAttributes.dis\
	StabilityLevel.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/tracing/dtrace

<$ROOT/mkfiles/mkjava
