<../../../../../../../../../mkconfig

DIRS=\
	algorithms\
	c14n\
	encryption\
	exceptions\
	keys\
	resource\
	signature\
	transforms\
	utils\

TARG=\
	Init.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/org/apache/xml/internal/security

<$ROOT/mkfiles/mkjava
<$ROOT/mkfiles/mksubdirs
