<../../../../../mkconfig

DIRS=\
	META-INF\

TARG=\
	Curve.dis\
	Dasher.dis\
	Helpers.dis\
	PiscesCache.dis\
	PiscesRenderingEngine.dis\
	PiscesTileGenerator.dis\
	Renderer.dis\
	Stroker.dis\
	TransformingPathConsumer2D.dis\

DISBIN=$ROOT/java/dis/java/java/sun/java2d/pisces

<$ROOT/mkfiles/mkjava
<$ROOT/mkfiles/mksubdirs
