<../../../../../../../../mkconfig

TARG=\
	MonitoredHostProvider.dis\
	PerfDataBuffer.dis\
	RemoteMonitoredVm.dis\
	RemoteVmManager.dis\

DISBIN=$ROOT/java/dis/java/java/sun/jvmstat/perfdata/monitor/protocol/rmi

<$ROOT/mkfiles/mkjava
