<../../../../../../mkconfig

TARG=\
	ClientVector.dis\
	HttpClient.dis\
	KeepAliveCache.dis\
	KeepAliveKey.dis\
	KeepAliveStream.dis\

DISBIN=$ROOT/java/dis/java/sun/net/www/http

<$ROOT/mkfiles/mkjava

ClientVector.dis:	KeepAliveCache.class
	j2d ClientVector.class

KeepAliveKey.dis:	KeepAliveCache.class
	j2d KeepAliveKey.class
