<../../../../../../mkconfig

DIRS=\
	spi\

TARG=\
	AgentInitializationException.dis\
	AgentLoadException.dis\
	AttachNotSupportedException.dis\
	AttachPermission.dis\
	VirtualMachine.dis\
	VirtualMachineDescriptor.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/tools/attach

<$ROOT/mkfiles/mkjava
<$ROOT/mkfiles/mksubdirs
