<../../../../mkconfig

TARG=\
	BigDecimal.dis\
	BigInteger.dis\
	BitSieve.dis\
	MathContext.dis\
	MutableBigInteger.dis\
	package-info.dis\
	RoundingMode.dis\
	SignedMutableBigInteger.dis\

DISBIN=$ROOT/java/dis/java/java/java/math

<$ROOT/mkfiles/mkjava
