<../../../../../../mkconfig

TARG=\
	AuthorizationDataEntry.dis\
	ExtendedGSSContext.dis\
	GSSUtil.dis\
	InquireSecContextPermission.dis\
	InquireType.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/security/jgss

<$ROOT/mkfiles/mkjava
