<../../../../../../../mkconfig

TARG=\
	ReferenceWrapper.dis\
	RegistryContext.dis\
	RegistryContextFactory.dis\
	RemoteReference.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/jndi/rmi/registry

<$ROOT/mkfiles/mkjava
