<../../../../../../../../../../../mkconfig

DIRS=\
	implementations\

TARG=\
	ResourceResolver.dis\
	ResourceResolverException.dis\
	ResourceResolverSpi.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/org/apache/xml/internal/security/utils/resolver

<$ROOT/mkfiles/mkjava
<$ROOT/mkfiles/mksubdirs
