<../../../../../mkconfig

TARG=\
	AnonymousClassLoader.dis\
	ConstantPoolParser.dis\
	ConstantPoolPatch.dis\
	ConstantPoolVisitor.dis\
	InvalidConstantPoolFormatException.dis\

DISBIN=$ROOT/java/dis/java/java/sun/invoke/anon

<$ROOT/mkfiles/mkjava
