<../../../../../../mkconfig

TARG=\
	JConsoleResources.dis\
	JConsoleResources_ja.dis\
	JConsoleResources_zh_CN.dis\

DISBIN=$ROOT/java/dis/java/java/sun/tools/jconsole/resources

<$ROOT/mkfiles/mkjava
