<../../../../../../mkconfig

DIRS=\
	META-INF\

TARG=\
	ExternalScriptable.dis\
	JavaAdapter.dis\
	JSAdapter.dis\
	RhinoClassShutter.dis\
	RhinoCompiledScript.dis\
	RhinoScriptEngine.dis\
	RhinoScriptEngineFactory.dis\
	RhinoTopLevel.dis\
	RhinoWrapFactory.dis\

DISBIN=$ROOT/java/dis/java/java/com/sun/script/javascript

<$ROOT/mkfiles/mkjava
<$ROOT/mkfiles/mksubdirs
